In [1]:
print("all ok")

all ok

In [2]:
import pandas as pd

In [3]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})

In [4]:
data

                    text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
BOW=CountVectorizer()

In [7]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [8]:
document_matrix=BOW.fit_transform(data["text"])

In [9]:
document_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

### Alphabatical sequence

In [10]:
BOW.vocabulary_

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

In [11]:
document_matrix[0].toarray()

array([[0, 1, 0, 1, 1]])

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

comment, cricket, give, people, watch

D2-> cricket watch cricket

0, 2, 0, 0, 1

In [12]:
document_matrix[1].toarray()

array([[0, 2, 0, 0, 1]])

In [13]:
document_matrix[2].toarray()

array([[1, 0, 1, 1, 0]])

In [14]:
document_matrix[3].toarray()

array([[1, 1, 1, 0, 0]])

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
bigram=CountVectorizer(ngram_range=(2,2))

In [17]:
bigramvocab=bigram.fit_transform(data["text"])

In [18]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

people watch cricket
cricket watch cricket
people give comment
cricket give comment

capture the information in sequence(count vectorizer)

uniq vocab from the above data
[('cricket give'),('cricket watch'),('give comment'),('people give'),('people watch'),('watch cricket')]


{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

custom logic:
you can create pair as per your wish

In [19]:
bigram.vocabulary_

{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

In [20]:
trigram=CountVectorizer(ngram_range=(3,3))

In [21]:
trigramvocab=trigram.fit_transform(data["text"])

In [22]:
trigram.vocabulary_

{'people watch cricket': 3,
 'cricket watch cricket': 1,
 'people give comment': 2,
 'cricket give comment': 0}

In [23]:
mix=CountVectorizer(ngram_range=(1,3))

In [24]:
mix_vocab=mix.fit_transform(data["text"])

In [25]:
mix.vocabulary_

{'people': 8,
 'watch': 13,
 'cricket': 1,
 'people watch': 11,
 'watch cricket': 14,
 'people watch cricket': 12,
 'cricket watch': 4,
 'cricket watch cricket': 5,
 'give': 6,
 'comment': 0,
 'people give': 9,
 'give comment': 7,
 'people give comment': 10,
 'cricket give': 2,
 'cricket give comment': 3}